### ISSUE TITLE
Sergey's to-do list

### ISSUE THREAD

**Issue by SergoFox123** [SergoFox123/Wild-Update-Plus#1]
- [ ] Add more blocks
- [ ] Add tree generation
- [ ] Add more types of trees
